### ISSUE TITLE
issuer entity format urn:oasis:names:tc:SAML:2.0:nameid-format:entity (Down for Sielte and Tim)

### ISSUE THREAD

**Issue by falco76** [italia/spid-sp-simplesamlphp#2]
Sielte and TIM drop Authn request if issuer format != "urn:oasis:names:tc:SAML:2.0:nameid-format:entity"
case sensitive and without any space

SAML2 library is complaint to saml-core-2.0-os 8.3.6

From saml-core-2.0-os 8.3.6, when the entity Format is used: "The NameQualifier, SPNameQualifier, and SPProvidedID attributes MUST be omitted"
         
Poste and Aruba are ok without any patch
i'm testing a solution on saml2 library and ssp to force SAML2 standard on single SP config ...

**Comment by falco76** [comment]
hi @umbros 
i solved see my saml2 library (i send pr to main project).
i submit soon ssp code but it require my saml2 library (if my pr is discarded)

**Comment by umbros** [comment]
10x @falco76 :-D

**Comment by falco76** [comment]
my patch is on simplesamlphp/saml2 library

https://github.com/simplesamlphp/saml2/pull/94
