### ISSUE TITLE
working directory

### ISSUE THREAD

**Issue by valerio-bozzolan** [italia/spid-sp-simplesamlphp#6]
Sono un po' confuso su quale dovrebbe essere la working directory assunta da questo comando del README:

    cp ../config-templates/config-spid.php config/config.php
    cp ../config-templates/authsources-spid.php config/authsources.php

Sempre se si intenda `simplespidphp`, forse dovrebbe essere così:

    cp config-templates/config-spid.php config/config.php
    cp config-templates/authsources-spid.php config/authsources.php

**Comment by rasky** [comment]
Fixed
